## Лабораторна робота №1
## Зчитування та первинне профілювання даних

**Student ID:** S04

У цьому notebook виконується зчитування та дослідження структури чотирьох джерел даних: `customers.csv`, `merchants.csv`, `products.csv` та `orders.csv`.

In [1]:
from pathlib import Path
import pandas as pd

In [2]:
root = Path.cwd()

if root.name == "notebooks":
    root = root.parent

In [3]:
orders = pd.read_csv(root / "data" / "raw" / "orders.csv")
display(orders.head())
orders.info()

,order_id,customer_id,merchant_id,created_at,order_status,currency,subtotal_amount,delivery_fee,discount_amount,total_amount
0,S04-O0000001,S04-C000762,S04-M00018,2025-09-01T09:12:01Z,delivered,UAH,133.52,87.08,0.0,220.60
1,S04-O0000002,S04-C000247,S04-M00036,2025-09-01T10:45:15Z,delivered,UAH,320.02,69.30,16.0,373.32
2,S04-O0000003,S04-C000746,S04-M00002,2025-09-01T11:06:31Z,delivered,UAH,211.30,62.64,0.0,273.94
3,S04-O0000004,S04-C000759,S04-M00027,2025-09-01T12:03:43Z,delivered,UAH,817.50,98.69,0.0,916.19
4,S04-O0000005,S04-C000364,S04-M00004,2025-09-01T12:25:06Z,delivered,UAH,346.98,65.12,0.0,412.10

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6001 entries, 0 to 6000
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   order_id         6001 non-null   object
 1   customer_id      6001 non-null   object
 2   merchant_id      6001 non-null   object
 3   created_at       6001 non-null   object
 4   order_status     6001 non-null   object
 5   currency         6001 non-null   object
 6   subtotal_amount  6001 non-null   float64
 7   delivery_fee     6001 non-null   float64
 8   discount_amount  6001 non-null   float64
 9   total_amount     6001 non-null   float64
dtypes: float64(4), object(6)
memory usage: 469.0+ KB

In [4]:
display(orders.tail())
display(orders.sample(5))

print("Shape:", orders.shape)
print("Columns:", orders.columns.tolist())
print("Index:", orders.index)
print("Dtypes:")
print(orders.dtypes)

,order_id,customer_id,merchant_id,created_at,order_status,currency,subtotal_amount,delivery_fee,discount_amount,total_amount
5996,S04-O0005997,S04-C000512,S04-M00034,2026-08-31T19:40:13Z,delivered,UAH,181.49,98.00,36.30,243.19
5997,S04-O0005998,S04-C000259,S04-M00018,2026-08-31T19:47:43Z,delivered,UAH,1582.02,0.00,79.10,1502.92
5998,S04-O0005999,S04-C000343,S04-M00034,2026-08-31T21:32:59Z,delivered,UAH,243.26,98.14,0.00,341.40
5999,S04-O0006000,S04-C000267,S04-M00019,2026-08-31T22:56:25Z,delivered,UAH,122.99,86.90,6.15,203.74
6000,S04-O0004432,S04-C000278,S04-M00009,2026-05-26T13:04:39Z,delivered,UAH,1212.72,0.00,0.00,1212.72

,order_id,customer_id,merchant_id,created_at,order_status,currency,subtotal_amount,delivery_fee,discount_amount,total_amount
1629,S04-O0001630,S04-C000116,S04-M00042,2025-12-04T22:32:27Z,delivered,UAH,1568.92,0.00,156.89,1412.03
4755,S04-O0004756,S04-C000022,S04-M00021,2026-06-14T15:09:26Z,delivered,UAH,588.93,84.69,0.00,673.62
3483,S04-O0003484,S04-C000330,S04-M00021,2026-03-29T17:57:47Z,delivered,UAH,822.78,77.31,0.00,900.09
4497,S04-O0004498,S04-C000687,S04-M00003,2026-05-30T12:05:16Z,refunded,UAH,485.18,92.70,48.52,529.36
2948,S04-O0002949,S04-C000611,S04-M00027,2026-02-25T19:11:10Z,delivered,UAH,430.22,86.39,0.00,516.61

Shape: (6001, 10)
Columns: ['order_id', 'customer_id', 'merchant_id', 'created_at', 'order_status', 'currency', 'subtotal_amount', 'delivery_fee', 'discount_amount', 'total_amount']
Index: RangeIndex(start=0, stop=6001, step=1)
Dtypes:
order_id            object
customer_id         object
merchant_id         object
created_at          object
order_status        object
currency            object
subtotal_amount    float64
delivery_fee       float64
discount_amount    float64
total_amount       float64
dtype: object

## Структура `orders.csv`

Файл `orders.csv` містить дані про замовлення. Один рядок представляє одне замовлення.

Таблиця містить 6001 рядок і 10 колонок. Поля `order_id`, `customer_id`, `merchant_id`, `created_at`, `order_status` і `currency` мають тип `object`, а поля із сумами — тип `float64`.

Поле `order_id` може бути ключем замовлення. Поле `customer_id` пов'язує замовлення з клієнтом, а `merchant_id` — із закладом.

За допомогою `head()` було переглянуто перші рядки, `tail()` — останні, а `sample()` — випадкові записи. `shape`, `columns`, `index`, `dtypes` та `info()` дали змогу визначити розмір і структуру таблиці та типи даних.

In [5]:
customers = pd.read_csv(root / "data" / "raw" / "customers.csv")
display(customers.head())
customers.info()

,customer_id,full_name,email,phone,city,service_zone_id,registered_at,customer_status
0,S04-C000001,Mariia Voloshyn,s04.customer000001@example.test,3.809975e+11,Lviv,LVI-Z02,2025-05-22T06:42:12.743711700Z,active
1,S04-C000002,Ivan Petrenko,s04.customer000002@example.test,3.809390e+11,Kyiv,KYI-Z03,2024-10-13T02:59:08.451585521Z,active
2,S04-C000003,Taras Havryliuk,s04.customer000003@example.test,3.807329e+11,Kyiv,KYI-Z03,2025-11-12T15:54:43.938054213Z,active
3,S04-C000004,Artem Shevchenko,s04.customer000004@example.test,3.809822e+11,Kyiv,KYI-Z05,2025-09-13T23:58:23.985200836Z,active
4,S04-C000005,Nazar Kravchenko,s04.customer000005@example.test,3.809795e+11,Kyiv,KYI-Z03,2025-09-11T04:01:16.026061957Z,active

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 801 entries, 0 to 800
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   customer_id      801 non-null    object
 1   full_name        801 non-null    object
 2   email            801 non-null    object
 3   phone            796 non-null    float64
 4   city             801 non-null    object
 5   service_zone_id  801 non-null    object
 6   registered_at    801 non-null    object
 7   customer_status  801 non-null    object
dtypes: float64(1), object(7)
memory usage: 50.2+ KB

In [6]:
display(customers.tail())
display(customers.sample(5))

print("Shape:", customers.shape)
print("Columns:", customers.columns.tolist())
print("Index:", customers.index)
print("Dtypes:")
print(customers.dtypes)

,customer_id,full_name,email,phone,city,service_zone_id,registered_at,customer_status
796,S04-C000797,Iryna Havryliuk,s04.customer000797@example.test,3.809600e+11,Kharkiv,KHA-Z03,2025-06-20T13:57:09.930836368Z,active
797,S04-C000798,Roman Romanenko,s04.customer000798@example.test,3.809802e+11,Kyiv,KYI-Z04,2024-11-04T12:07:31.986928310Z,active
798,S04-C000799,Oleksandr Vasylenko,s04.customer000799@example.test,3.809810e+11,Kyiv,KYI-Z04,2025-10-06T01:15:56.176221508Z,active
799,S04-C000800,Tetiana Tkachenko,s04.customer000800@example.test,3.809724e+11,Kyiv,KYI-Z01,2025-10-17T15:10:53.208709473Z,active
800,S04-C000756,Olena Yaremchuk,s04.customer000756@example.test,3.807350e+11,Odesa,ODE-Z03,2024-08-02T23:27:47.940919274Z,active

,customer_id,full_name,email,phone,city,service_zone_id,registered_at,customer_status
257,S04-C000258,Vasyl Kravets,s04.customer000258@example.test,3.809760e+11,Dnipro,DNI-Z03,2025-03-21T13:02:34.431380470Z,active
29,S04-C000030,Artem Polishchuk,s04.customer000030@example.test,3.809876e+11,Kharkiv,KHA-Z01,2024-05-30T07:22:02.470460669Z,active
96,S04-C000097,Artem Romanenko,s04.customer000097@example.test,3.809327e+11,Odesa,ODE-Z03,2025-06-22T11:31:03.008377500Z,active
763,S04-C000764,Ivan Savchenko,s04.customer000764@example.test,3.806792e+11,Dnipro,DNI-Z01,2025-03-29T17:31:23.074578189Z,active
749,S04-C000750,Artem Zakharchenko,s04.customer000750@example.test,3.809386e+11,Dnipro,DNI-Z03,2024-04-13T17:18:50.476013107Z,active

Shape: (801, 8)
Columns: ['customer_id', 'full_name', 'email', 'phone', 'city', 'service_zone_id', 'registered_at', 'customer_status']
Index: RangeIndex(start=0, stop=801, step=1)
Dtypes:
customer_id         object
full_name           object
email               object
phone              float64
city                object
service_zone_id     object
registered_at       object
customer_status     object
dtype: object

## Структура `customers.csv`

Файл `customers.csv` містить дані про клієнтів. Один рядок представляє одного клієнта.

Таблиця містить 801 рядок і 8 колонок. Більшість колонок мають тип `object`, а поле `phone` має тип `float64`.

Поле `customer_id` може бути ключем клієнта. Поле `service_zone_id` містить ідентифікатор зони обслуговування.

За допомогою `head()` було переглянуто перші рядки, `tail()` — останні, а `sample()` — випадкові записи. `shape`, `columns`, `index`, `dtypes` та `info()` дали змогу визначити розмір і структуру таблиці та типи даних.

У колонці `phone` є пропущені значення: 796 непорожніх значень із 801 рядка.

In [7]:
merchants = pd.read_csv(root / "data" / "raw" / "merchants.csv")
display(merchants.head())
merchants.info()

,merchant_id,merchant_name,merchant_type,city,service_zone_id,opened_at,merchant_status
0,S04-M00001,Urban Place 01,restaurant,Kharkiv,KHA-Z01,2021-08-15T19:41:55.282076799Z,active
1,S04-M00002,Family Foods 02,grocery,Dnipro,DNI-Z01,2020-09-01T12:12:31.911779248Z,active
2,S04-M00003,Urban House 03,restaurant,Lviv,LVI-Z01,2023-05-05T02:48:07.729354511Z,active
3,S04-M00004,Family Kitchen 04,restaurant,Lviv,LVI-Z04,2023-07-06T22:32:32.757253098Z,active
4,S04-M00005,Family Place 05,restaurant,Kyiv,KYI-Z05,2022-06-16T12:15:17.083753052Z,active

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 43 entries, 0 to 42
Data columns (total 7 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   merchant_id      43 non-null     object
 1   merchant_name    43 non-null     object
 2   merchant_type    43 non-null     object
 3   city             43 non-null     object
 4   service_zone_id  43 non-null     object
 5   opened_at        43 non-null     object
 6   merchant_status  43 non-null     object
dtypes: object(7)
memory usage: 2.5+ KB

In [8]:
display(merchants.tail())
display(merchants.sample(5))

print("Shape:", merchants.shape)
print("Columns:", merchants.columns.tolist())
print("Index:", merchants.index)
print("Dtypes:")
print(merchants.dtypes)

,merchant_id,merchant_name,merchant_type,city,service_zone_id,opened_at,merchant_status
38,S04-M00039,Street Kitchen 39,restaurant,Kharkiv,KHA-Z02,2025-02-18T10:56:51.881795885Z,active
39,S04-M00040,Daily Market 40,convenience,Lviv,LVI-Z01,2022-01-17T05:02:29.169188817Z,paused
40,S04-M00041,Local Table 41,restaurant,Lviv,LVI-Z01,2024-05-26T02:54:27.682158219Z,active
41,S04-M00042,Street Bistro 42,restaurant,Kyiv,KYI-Z02,2020-03-29T20:20:02.470493059Z,active
42,S04-M00018,Craft Bakery 18,bakery,Kyiv,KYI-Z04,2022-08-07T21:59:34.100564095Z,active

,merchant_id,merchant_name,merchant_type,city,service_zone_id,opened_at,merchant_status
18,S04-M00019,Daily Foods 19,grocery,Kharkiv,KHA-Z01,2024-10-03T13:38:12.706305668Z,active
5,S04-M00006,Craft Table 06,restaurant,Lviv,LVI-Z02,2020-04-26T09:35:52.737355856Z,active
36,S04-M00037,Friendly Paws 37,pet_store,Dnipro,DNI-Z02,2025-02-27T13:02:46.543924516Z,active
20,S04-M00021,Craft Oven 21,bakery,Kharkiv,KHA-Z01,2023-04-15T00:04:58.168218089Z,active
9,S04-M00010,Care Care 10,pharmacy,Odesa,ODE-Z01,2024-10-04T04:54:17.396476229Z,active

Shape: (43, 7)
Columns: ['merchant_id', 'merchant_name', 'merchant_type', 'city', 'service_zone_id', 'opened_at', 'merchant_status']
Index: RangeIndex(start=0, stop=43, step=1)
Dtypes:
merchant_id        object
merchant_name      object
merchant_type      object
city               object
service_zone_id    object
opened_at          object
merchant_status    object
dtype: object

## Структура `merchants.csv`

Файл `merchants.csv` містить дані про заклади. Один рядок представляє один заклад.

Таблиця містить 43 рядки і 7 колонок. Усі колонки після зчитування мають тип `object`.

Поле `merchant_id` може бути ключем закладу. Поле `service_zone_id` містить ідентифікатор зони обслуговування. Поле `opened_at` містить дату відкриття закладу.

За допомогою `head()` було переглянуто перші рядки, `tail()` — останні, а `sample()` — випадкові записи. `shape`, `columns`, `index`, `dtypes` та `info()` дали змогу визначити розмір і структуру таблиці та типи даних.

In [9]:
products = pd.read_csv(root / "data" / "raw" / "products.csv")
display(products.head())
products.info()

,product_id,merchant_id,product_name,category,unit_price_uah,is_active,updated_at
0,S04-P000001,S04-M00001,Brownie,desserts,86.38,True,2025-08-09T21:50:40.807641267Z
1,S04-P000002,S04-M00001,California Roll,sushi,214.30,True,2026-06-24T06:45:33.279953678Z
2,S04-P000003,S04-M00001,Brownie,desserts,114.66,True,2025-12-09T19:15:04.566956542Z
3,S04-P000004,S04-M00001,Green Bowl,salads,135.63,True,2026-05-02T06:46:03.034497024Z
4,S04-P000005,S04-M00001,Shrimp Set,sushi,327.41,True,2026-06-04T21:46:15.711980650Z

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 498 entries, 0 to 497
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   product_id      498 non-null    object
 1   merchant_id     498 non-null    object
 2   product_name    498 non-null    object
 3   category        498 non-null    object
 4   unit_price_uah  498 non-null    float64
 5   is_active       498 non-null    bool
 6   updated_at      498 non-null    object
dtypes: bool(1), float64(1), object(5)
memory usage: 24.0+ KB

In [10]:
display(products.tail())
display(products.sample(5))

print("Shape:", products.shape)
print("Columns:", products.columns.tolist())
print("Index:", products.index)
print("Dtypes:")
print(products.dtypes)

,product_id,merchant_id,product_name,category,unit_price_uah,is_active,updated_at
493,S04-P000494,S04-M00042,Chicken Burger,burgers,189.12,True,2025-09-04T01:39:45.445469199Z
494,S04-P000495,S04-M00042,Salmon Roll,sushi,344.58,True,2025-10-13T07:31:41.238243557Z
495,S04-P000496,S04-M00042,Veggie Burger,burgers,311.71,True,2026-02-05T17:26:48.763174238Z
496,S04-P000497,S04-M00042,Veggie Burger,burgers,310.06,True,2025-12-21T21:25:14.377283897Z
497,S04-P000474,S04-M00040,Energy Drink,beverages,49.03,True,2025-11-10T05:50:29.163601925Z

,product_id,merchant_id,product_name,category,unit_price_uah,is_active,updated_at
385,S04-P000386,S04-M00033,Cola,beverages,33.24,True,2025-11-30T08:52:42.716530997Z
448,S04-P000449,S04-M00039,Veggie Pizza,pizza,373.93,True,2025-09-18T14:53:04.075274840Z
42,S04-P000043,S04-M00004,Veggie Pizza,pizza,221.35,True,2025-09-28T21:42:11.191870206Z
417,S04-P000418,S04-M00036,Hand Soap,personal_care,103.56,True,2025-12-27T23:33:58.695731331Z
194,S04-P000195,S04-M00016,Baguette,bread,51.12,True,2026-02-10T09:48:54.798542137Z

Shape: (498, 7)
Columns: ['product_id', 'merchant_id', 'product_name', 'category', 'unit_price_uah', 'is_active', 'updated_at']
Index: RangeIndex(start=0, stop=498, step=1)
Dtypes:
product_id         object
merchant_id        object
product_name       object
category           object
unit_price_uah    float64
is_active            bool
updated_at         object
dtype: object

### Структура `products.csv`

Файл `products.csv` містить дані про товари. Один рядок представляє один товар.

Таблиця містить 498 рядків і 7 колонок. Поля `product_id`, `merchant_id`, `product_name`, `category` та `updated_at` мають тип `object`. Поле `unit_price_uah` має тип `float64`, а `is_active` — тип `bool`.

Поле `product_id` може бути ключем товару. Поле `merchant_id` пов'язує товар із відповідним закладом із таблиці `merchants.csv`.

За допомогою `head()` було переглянуто перші рядки, `tail()` — останні, а `sample()` — випадкові записи. `shape`, `columns`, `index`, `dtypes` та `info()` дали змогу визначити розмір і структуру таблиці та типи даних.

## Дослідження таблиці orders

In [11]:
orders.describe()

       subtotal_amount  delivery_fee  discount_amount  total_amount
count      6001.000000   6001.000000      6001.000000   6001.000000
mean        524.918220     73.640910        15.620543    582.961446
std         454.916431     27.816916        37.357158    432.253441
min           1.350000      0.000000         0.000000      3.190000
25%         188.100000     70.390000         0.000000    263.240000
50%         385.530000     79.470000         0.000000    454.490000
75%         730.980000     88.850000         9.810000    791.030000
max        3443.470000    141.280000       350.000000   3443.470000

In [12]:
orders.nunique()

order_id           6000
customer_id         771
merchant_id          43
created_at         5999
order_status          6
currency              4
subtotal_amount    5819
delivery_fee       2349
discount_amount    1624
total_amount       5835
dtype: int64

In [13]:
print("Order status:")
print(orders["order_status"].value_counts(dropna=False))

print("\nCurrency:")
print(orders["currency"].value_counts(dropna=False))

Order status:
order_status
delivered             4969
cancelled              458
refunded               225
partially_refunded     211
failed                 137
in_progress              1
Name: count, dtype: int64

Currency:
currency
UAH     5928
USD       47
EUR       25
UA H       1
Name: count, dtype: int64

In [14]:
missing_count = orders.isna().sum()
missing_share = orders.isna().mean() * 100

pd.DataFrame({
    "missing_count": missing_count,
    "missing_share_%": missing_share
})

                 missing_count  missing_share_%
order_id                     0              0.0
customer_id                  0              0.0
merchant_id                  0              0.0
created_at                   0              0.0
order_status                 0              0.0
currency                     0              0.0
subtotal_amount              0              0.0
delivery_fee                 0              0.0
discount_amount              0              0.0
total_amount                 0              0.0

In [15]:
text_columns = orders.select_dtypes(include="object").columns

for col in text_columns:
    empty_count = (orders[col] == "").sum()
    whitespace_count = orders[col].astype(str).str.fullmatch(r"\s+").sum()
    
    print(
        col,
        "- empty:", empty_count,
        "- whitespace:", whitespace_count
    )

order_id - empty: 0 - whitespace: 0
customer_id - empty: 0 - whitespace: 0
merchant_id - empty: 0 - whitespace: 0
created_at - empty: 0 - whitespace: 0
order_status - empty: 0 - whitespace: 0
currency - empty: 0 - whitespace: 0

In [16]:
print("Full duplicates:", orders.duplicated().sum())
print("Duplicate order_id:", orders.duplicated(subset=["order_id"]).sum())

Full duplicates: 1
Duplicate order_id: 1

In [17]:
display(orders[orders.duplicated(keep=False)])

display(
    orders[orders.duplicated(subset=["order_id"], keep=False)]
    .sort_values("order_id")
)

,order_id,customer_id,merchant_id,created_at,order_status,currency,subtotal_amount,delivery_fee,discount_amount,total_amount
4431,S04-O0004432,S04-C000278,S04-M00009,2026-05-26T13:04:39Z,delivered,UAH,1212.72,0.0,0.0,1212.72
6000,S04-O0004432,S04-C000278,S04-M00009,2026-05-26T13:04:39Z,delivered,UAH,1212.72,0.0,0.0,1212.72

,order_id,customer_id,merchant_id,created_at,order_status,currency,subtotal_amount,delivery_fee,discount_amount,total_amount
4431,S04-O0004432,S04-C000278,S04-M00009,2026-05-26T13:04:39Z,delivered,UAH,1212.72,0.0,0.0,1212.72
6000,S04-O0004432,S04-C000278,S04-M00009,2026-05-26T13:04:39Z,delivered,UAH,1212.72,0.0,0.0,1212.72

In [18]:
orders_dates = pd.to_datetime(orders["created_at"], errors="coerce")

print("Min date:", orders_dates.min())
print("Max date:", orders_dates.max())
print("Invalid dates:", orders_dates.isna().sum())

Min date: 2025-09-01 09:12:01+00:00
Max date: 2026-08-31 22:56:25+00:00
Invalid dates: 2

In [19]:
invalid_orders_dates = orders[orders_dates.isna()]

display(invalid_orders_dates[
    ["order_id", "created_at"]
])

          order_id           created_at
5215  S04-O0005216  2026-19-45 25:61:00
5283  S04-O0005284     17/07/2026 21:36

In [20]:
numeric_columns = [
    "subtotal_amount",
    "delivery_fee",
    "discount_amount",
    "total_amount"
]

for col in numeric_columns:
    print(f"\n{col}")
    print("Min:", orders[col].min())
    print("Max:", orders[col].max())
    print("Zero:", (orders[col] == 0).sum())
    print("Negative:", (orders[col] < 0).sum())

subtotal_amount
Min: 1.35
Max: 3443.47
Zero: 0
Negative: 0

delivery_fee
Min: 0.0
Max: 141.28
Zero: 569
Negative: 0

discount_amount
Min: 0.0
Max: 350.0
Zero: 4251
Negative: 0

total_amount
Min: 3.19
Max: 3443.47
Zero: 0
Negative: 0

## Дослідження таблиці customers

In [21]:
display(customers.describe(include="all"))

print("Unique values:")
print(customers.nunique())

print("\nCustomer status:")
print(customers["customer_status"].value_counts(dropna=False))

print("\nCity:")
print(customers["city"].value_counts(dropna=False))

,customer_id,full_name,email,phone,city,service_zone_id,registered_at,customer_status
count,801,801,801,7.960000e+02,801,801,801,801
unique,800,512,799,NaN,6,18,800,3
top,S04-C000756,Oleksandr Melnyk,s04.customer000712@example.test,NaN,Kyiv,DNI-Z02,2024-08-02T23:27:47.940919274Z,active
freq,2,5,2,NaN,216,56,2,752
mean,NaN,NaN,NaN,3.808120e+11,NaN,NaN,NaN,NaN
std,NaN,NaN,NaN,1.643548e+08,NaN,NaN,NaN,NaN
min,NaN,NaN,NaN,3.805002e+11,NaN,NaN,NaN,NaN
25%,NaN,NaN,NaN,3.806710e+11,NaN,NaN,NaN,NaN
50%,NaN,NaN,NaN,3.809303e+11,NaN,NaN,NaN,NaN
75%,NaN,NaN,NaN,3.809707e+11,NaN,NaN,NaN,NaN
max,NaN,NaN,NaN,3.809999e+11,NaN,NaN,NaN,NaN

Unique values:
customer_id        800
full_name          512
email              799
phone              795
city                 6
service_zone_id     18
registered_at      800
customer_status      3
dtype: int64

Customer status:
customer_status
active       752
inactive      30
suspended     19
Name: count, dtype: int64

City:
city
Kyiv       216
Lviv       199
Kharkiv    131
Odesa      130
Dnipro     124
 Odesa       1
Name: count, dtype: int64

In [22]:
missing_count = customers.isna().sum()
missing_share = customers.isna().mean() * 100

pd.DataFrame({
    "missing_count": missing_count,
    "missing_share_%": missing_share
})

                 missing_count  missing_share_%
customer_id                  0          0.00000
full_name                    0          0.00000
email                        0          0.00000
phone                        5          0.62422
city                         0          0.00000
service_zone_id              0          0.00000
registered_at                0          0.00000
customer_status              0          0.00000

In [23]:
text_columns = customers.select_dtypes(include="object").columns

for col in text_columns:
    empty_count = (customers[col] == "").sum()
    whitespace_count = customers[col].astype(str).str.fullmatch(r"\s+").sum()

    print(
        col,
        "- empty:", empty_count,
        "- whitespace:", whitespace_count
    )

customer_id - empty: 0 - whitespace: 0
full_name - empty: 0 - whitespace: 0
email - empty: 0 - whitespace: 0
city - empty: 0 - whitespace: 0
service_zone_id - empty: 0 - whitespace: 0
registered_at - empty: 0 - whitespace: 0
customer_status - empty: 0 - whitespace: 0

In [24]:
print("Full duplicates:", customers.duplicated().sum())
print("Duplicate customer_id:", customers.duplicated(subset=["customer_id"]).sum())

Full duplicates: 1
Duplicate customer_id: 1

In [25]:
display(customers[customers.duplicated(keep=False)])

display(
    customers[customers.duplicated(subset=["customer_id"], keep=False)]
    .sort_values("customer_id")
)

,customer_id,full_name,email,phone,city,service_zone_id,registered_at,customer_status
755,S04-C000756,Olena Yaremchuk,s04.customer000756@example.test,3.807350e+11,Odesa,ODE-Z03,2024-08-02T23:27:47.940919274Z,active
800,S04-C000756,Olena Yaremchuk,s04.customer000756@example.test,3.807350e+11,Odesa,ODE-Z03,2024-08-02T23:27:47.940919274Z,active

,customer_id,full_name,email,phone,city,service_zone_id,registered_at,customer_status
755,S04-C000756,Olena Yaremchuk,s04.customer000756@example.test,3.807350e+11,Odesa,ODE-Z03,2024-08-02T23:27:47.940919274Z,active
800,S04-C000756,Olena Yaremchuk,s04.customer000756@example.test,3.807350e+11,Odesa,ODE-Z03,2024-08-02T23:27:47.940919274Z,active

In [26]:
customers_dates = pd.to_datetime(customers["registered_at"], errors="coerce")

print("Min date:", customers_dates.min())
print("Max date:", customers_dates.max())
print("Invalid dates:", customers_dates.isna().sum())

Min date: 2024-03-10 20:48:57.433085283+00:00
Max date: 2026-08-29 15:43:58.687869358+00:00
Invalid dates: 0

## Дослідження таблиці merchants

In [27]:
display(merchants.describe(include="all"))

print("Unique values:")
print(merchants.nunique())

print("\nMerchant type:")
print(merchants["merchant_type"].value_counts(dropna=False))

print("\nCity:")
print(merchants["city"].value_counts(dropna=False))

print("\nMerchant status:")
print(merchants["merchant_status"].value_counts(dropna=False))

,merchant_id,merchant_name,merchant_type,city,service_zone_id,opened_at,merchant_status
count,43,43,43,43,43,43,43
unique,42,42,7,5,17,42,2
top,S04-M00018,Craft Bakery 18,restaurant,Lviv,LVI-Z01,2022-08-07T21:59:34.100564095Z,active
freq,2,2,13,13,7,2,40

Unique values:
merchant_id        42
merchant_name      42
merchant_type       7
city                5
service_zone_id    17
opened_at          42
merchant_status     2
dtype: int64

Merchant type:
merchant_type
restaurant     13
grocery        10
bakery          6
pharmacy        6
convenience     4
pet_store       3
RESTAURANT      1
Name: count, dtype: int64

City:
city
Lviv       13
Kyiv       12
Kharkiv     9
Dnipro      6
Odesa       3
Name: count, dtype: int64

Merchant status:
merchant_status
active    40
paused     3
Name: count, dtype: int64

In [28]:
missing_count = merchants.isna().sum()
missing_share = merchants.isna().mean() * 100

pd.DataFrame({
    "missing_count": missing_count,
    "missing_share_%": missing_share
})

                 missing_count  missing_share_%
merchant_id                  0              0.0
merchant_name                0              0.0
merchant_type                0              0.0
city                         0              0.0
service_zone_id              0              0.0
opened_at                    0              0.0
merchant_status              0              0.0

In [29]:
text_columns = merchants.select_dtypes(include="object").columns

for col in text_columns:
    empty_count = (merchants[col] == "").sum()
    whitespace_count = merchants[col].astype(str).str.fullmatch(r"\s+").sum()

    print(
        col,
        "- empty:", empty_count,
        "- whitespace:", whitespace_count
    )

merchant_id - empty: 0 - whitespace: 0
merchant_name - empty: 0 - whitespace: 0
merchant_type - empty: 0 - whitespace: 0
city - empty: 0 - whitespace: 0
service_zone_id - empty: 0 - whitespace: 0
opened_at - empty: 0 - whitespace: 0
merchant_status - empty: 0 - whitespace: 0

In [30]:
print("Full duplicates:", merchants.duplicated().sum())
print("Duplicate merchant_id:", merchants.duplicated(subset=["merchant_id"]).sum())

Full duplicates: 1
Duplicate merchant_id: 1

In [31]:
display(merchants[merchants.duplicated(keep=False)])

display(
    merchants[merchants.duplicated(subset=["merchant_id"], keep=False)]
    .sort_values("merchant_id")
)

,merchant_id,merchant_name,merchant_type,city,service_zone_id,opened_at,merchant_status
17,S04-M00018,Craft Bakery 18,bakery,Kyiv,KYI-Z04,2022-08-07T21:59:34.100564095Z,active
42,S04-M00018,Craft Bakery 18,bakery,Kyiv,KYI-Z04,2022-08-07T21:59:34.100564095Z,active

,merchant_id,merchant_name,merchant_type,city,service_zone_id,opened_at,merchant_status
17,S04-M00018,Craft Bakery 18,bakery,Kyiv,KYI-Z04,2022-08-07T21:59:34.100564095Z,active
42,S04-M00018,Craft Bakery 18,bakery,Kyiv,KYI-Z04,2022-08-07T21:59:34.100564095Z,active

In [32]:
merchants_dates = pd.to_datetime(merchants["opened_at"], errors="coerce")

print("Min date:", merchants_dates.min())
print("Max date:", merchants_dates.max())
print("Invalid dates:", merchants_dates.isna().sum())

Min date: 2019-10-29 04:04:05.352506715+00:00
Max date: 2025-02-27 13:02:46.543924516+00:00
Invalid dates: 0

## Дослідження таблиці products

In [33]:
display(products.describe(include="all"))

print("Unique values:")
print(products.nunique())

print("\nCategory:")
print(products["category"].value_counts(dropna=False))

print("\nIs active:")
print(products["is_active"].value_counts(dropna=False))

,product_id,merchant_id,product_name,category,unit_price_uah,is_active,updated_at
count,498,498,498,498,498.000000,498,498
unique,497,43,101,24,NaN,2,497
top,S04-P000474,S04-M00001,Shrimp Set,salads,NaN,True,2025-11-10T05:50:29.163601925Z
freq,2,16,14,38,NaN,480,2
mean,NaN,NaN,NaN,NaN,183.480301,NaN,NaN
std,NaN,NaN,NaN,NaN,138.150192,NaN,NaN
min,NaN,NaN,NaN,NaN,0.000000,NaN,NaN
25%,NaN,NaN,NaN,NaN,78.380000,NaN,NaN
50%,NaN,NaN,NaN,NaN,148.485000,NaN,NaN
75%,NaN,NaN,NaN,NaN,247.662500,NaN,NaN
max,NaN,NaN,NaN,NaN,779.880000,NaN,NaN

Unique values:
product_id        497
merchant_id        43
product_name      101
category           24
unit_price_uah    493
is_active           2
updated_at        497
dtype: int64

Category:
category
salads             38
beverages          38
sushi              37
burgers            36
desserts           33
pizza              33
household          32
bakery             24
produce            22
dairy              20
health             20
vitamins           19
snacks             17
bread              17
baby_care          15
personal_care      15
coffee             14
pet_food           13
pet_care           12
pet_accessories    11
cakes              11
pastries           10
ready_meals        10
 Dairy              1
Name: count, dtype: int64

Is active:
is_active
True     480
False     18
Name: count, dtype: int64

In [34]:
missing_count = products.isna().sum()
missing_share = products.isna().mean() * 100

pd.DataFrame({
    "missing_count": missing_count,
    "missing_share_%": missing_share
})

                missing_count  missing_share_%
product_id                  0              0.0
merchant_id                 0              0.0
product_name                0              0.0
category                    0              0.0
unit_price_uah              0              0.0
is_active                   0              0.0
updated_at                  0              0.0

In [35]:
text_columns = products.select_dtypes(include="object").columns

for col in text_columns:
    empty_count = (products[col] == "").sum()
    whitespace_count = products[col].astype(str).str.fullmatch(r"\s+").sum()

    print(
        col,
        "- empty:", empty_count,
        "- whitespace:", whitespace_count
    )

product_id - empty: 0 - whitespace: 0
merchant_id - empty: 0 - whitespace: 0
product_name - empty: 0 - whitespace: 0
category - empty: 0 - whitespace: 0
updated_at - empty: 0 - whitespace: 0

In [36]:
print("Full duplicates:", products.duplicated().sum())
print("Duplicate product_id:", products.duplicated(subset=["product_id"]).sum())

Full duplicates: 1
Duplicate product_id: 1

In [37]:
display(products[products.duplicated(keep=False)])

display(
    products[products.duplicated(subset=["product_id"], keep=False)]
    .sort_values("product_id")
)

,product_id,merchant_id,product_name,category,unit_price_uah,is_active,updated_at
473,S04-P000474,S04-M00040,Energy Drink,beverages,49.03,True,2025-11-10T05:50:29.163601925Z
497,S04-P000474,S04-M00040,Energy Drink,beverages,49.03,True,2025-11-10T05:50:29.163601925Z

,product_id,merchant_id,product_name,category,unit_price_uah,is_active,updated_at
473,S04-P000474,S04-M00040,Energy Drink,beverages,49.03,True,2025-11-10T05:50:29.163601925Z
497,S04-P000474,S04-M00040,Energy Drink,beverages,49.03,True,2025-11-10T05:50:29.163601925Z

In [38]:
products_dates = pd.to_datetime(products["updated_at"], errors="coerce")

print("Min date:", products_dates.min())
print("Max date:", products_dates.max())
print("Invalid dates:", products_dates.isna().sum())

Min date: 2025-08-02 04:05:13.081910480+00:00
Max date: 2026-08-30 20:26:50.483491008+00:00
Invalid dates: 0

In [39]:
print("Min price:", products["unit_price_uah"].min())
print("Max price:", products["unit_price_uah"].max())
print("Zero prices:", (products["unit_price_uah"] == 0).sum())
print("Negative prices:", (products["unit_price_uah"] < 0).sum())

Min price: 0.0
Max price: 779.88
Zero prices: 1
Negative prices: 0

In [40]:
missing_customer_refs = orders[
    ~orders["customer_id"].isin(customers["customer_id"])
]

print("Missing customer references:", len(missing_customer_refs))

display(
    missing_customer_refs[
        ["order_id", "customer_id"]
    ].head()
)

Missing customer references: 1

          order_id  customer_id
4998  S04-O0004999  S04-C999999

In [41]:
missing_order_merchant_refs = orders[
    ~orders["merchant_id"].isin(merchants["merchant_id"])
]

print("Missing merchant references in orders:", len(missing_order_merchant_refs))

display(
    missing_order_merchant_refs[
        ["order_id", "merchant_id"]
    ].head()
)

Missing merchant references in orders: 1

          order_id merchant_id
3185  S04-O0003186  S04-M99998

In [42]:
missing_product_merchant_refs = products[
    ~products["merchant_id"].isin(merchants["merchant_id"])
]

print("Missing merchant references in products:", len(missing_product_merchant_refs))

display(
    missing_product_merchant_refs[
        ["product_id", "merchant_id"]
    ].head()
)

Missing merchant references in products: 1

      product_id merchant_id
197  S04-P000198  S04-M99999